using System;
using System.Collections.Generic;

namespace SisWeb.EF.Models
{
    public partial class JednotkyTypyvzorkuVeliciny
    {
        public int JednotkaTypvzorkuVelicinaId { get; set; }
        public string Typ { get; set; }
        public int? Chlormethan { get; set; }
        public int? Dichlormethan { get; set; }
        public int? Trichlormethan { get; set; }
        public int? Tetrachlormethan { get; set; }
        public int? Dichlorethan11 { get; set; }
        public int? Dichlorethan12 { get; set; }
        public int? Vc { get; set; }
        public int? Dce11 { get; set; }
        public int? CDce12 { get; set; }
        public int? TDce12 { get; set; }
        public int? Tce { get; set; }
        public int? Pce { get; set; }
        public int? Trichlorethan111 { get; set; }
        public int? Trichlorethan112 { get; set; }
        public int? Tetrachlorethan1112 { get; set; }
        public int? Tetrachlorethan1122 { get; set; }
        public int? Dichlorpropan12 { get; set; }
        public int? Trichlorpropan123 { get; set; }
        public int? Dichlorpropylen11 { get; set; }
        public int? Hexachlorobutadien { get; set; }
        public int? Chlorbenzen { get; set; }
        public int? Dichlorbenzen12 { get; set; }
        public int? Dichlorbenzen13 { get; set; }
        public int? Dichlorbenzen14 { get; set; }
        public int? Trichlorbenzeny { get; set; }
        public int? Aox { get; set; }
        public int? Teq { get; set; }
        public int? Dichlorbenzeny { get; set; }
        public int? Trichlorbenzen123 { get; set; }
        public int? Trichlorbenzen124 { get; set; }
        public int? Trichlorbenzen135 { get; set; }
        public int? Tetrachlorbenzeny { get; set; }
        public int? Pentachlorbenzen { get; set; }
        public int? Hexachlorbenzen { get; set; }
        public int? SumaClu { get; set; }
        public int? SumaClm { get; set; }
        public int? SumaCle { get; set; }
        public int? SumaCluDleRozhodnuti { get; set; }
        public int? SumaDce { get; set; }
        public int? SumaCb { get; set; }
        public int? SumaHch { get; set; }
        public int? SumaHchBezEhch { get; set; }
        public int? AmonneIonty { get; set; }
        public int? Chloridy { get; set; }
        public int? Bromidy { get; set; }
        public int? Dusicnany { get; set; }
        public int? Dusitany { get; set; }
        public int? Fluoridy { get; set; }
        public int? Knk45 { get; set; }
        public int? Znk83 { get; set; }
        public int? Ph { get; set; }
        public int? Sirany { get; set; }
        public int? Sulfidy { get; set; }
        public int? Siricitany { get; set; }
        public int? SulfanVolny { get; set; }
        public int? Konduktivita { get; set; }
        public int? Fosforecnany { get; set; }
        public int? Co2AgresivniVypocet { get; set; }
        public int? Co2VolnyVypocet { get; set; }
        public int? Hydrogenuhlicitany { get; set; }
        public int? Uhlicitany { get; set; }
        public int? KolonieAerobni { get; set; }
        public int? KolonieAnaerobni { get; set; }
        public int? ChskCr { get; set; }
        public int? Ras { get; set; }
        public int? Nl105 { get; set; }
        public int? Rozpustene { get; set; }
        public int? Draslik { get; set; }
        public int? OxidKremicity { get; set; }
        public int? Sodik { get; set; }
        public int? Vapnik { get; set; }
        public int? Lithium { get; set; }
        public int? Arsen { get; set; }
        public int? PCelkovy { get; set; }
        public int? NCelkovy { get; set; }
        public int? Bsk5 { get; set; }
        public int? TvrdostCelkem { get; set; }
        public int? MineralizaceCelkem { get; set; }
        public int? ObjemovaHmotnost { get; set; }
        public int? Sirouhlik { get; set; }
        public int? KyanidyCelkove { get; set; }
        public int? KyanidyVolne { get; set; }
        public int? Kmno4 { get; set; }
        public int? H2o2 { get; set; }
        public int? AlfaAktivita { get; set; }
        public int? BetaAktivita { get; set; }
        public int? Barva { get; set; }
        public int? Sediment { get; set; }
        public int? Pach { get; set; }
        public int? Baryum { get; set; }
        public int? Berylium { get; set; }
        public int? Horcik { get; set; }
        public int? Hlinik { get; set; }
        public int? Chrom { get; set; }
        public int? Kadmium { get; set; }
        public int? Kobalt { get; set; }
        public int? Mangan { get; set; }
        public int? Med { get; set; }
        public int? Molybden { get; set; }
        public int? Nikl { get; set; }
        public int? Olovo { get; set; }
        public int? Rtut { get; set; }
        public int? Vanad { get; set; }
        public int? Zinek { get; set; }
        public int? Zelezo { get; set; }
        public int? Fe2 { get; set; }
        public int? Fe0 { get; set; }
        public int? ChskMn { get; set; }
        public int? ChemickyTypVody { get; set; }
        public int? Tic { get; set; }
        public int? Brru { get; set; }
        public int? LatkyVeskere { get; set; }
        public int? Doc { get; set; }
        public int? Toc { get; set; }
        public int? Nel { get; set; }
        public int? UhlovodikyC10C40 { get; set; }
        public int? Benzen { get; set; }
        public int? Toluen { get; set; }
        public int? Ethylbenzen { get; set; }
        public int? Xyleny { get; set; }
        public int? Styren { get; set; }
        public int? Naftalen { get; set; }
        public int? Methan { get; set; }
        public int? Ethan { get; set; }
        public int? Ethen { get; set; }
        public int? KyselinaCitronova { get; set; }
        public int? Mtbe { get; set; }
        public int? SumaBtex { get; set; }
        public int? Fenol { get; set; }
        public int? Kresoly { get; set; }
        public int? Dimethylfenoly { get; set; }
        public int? VyssiFenoly { get; set; }
        public int? Edta { get; set; }
        public int? NaFluorescein { get; set; }
        public int? O2 { get; set; }
        public int? Tlak { get; set; }
        public int? Pid118 { get; set; }
        public int? Ch4 { get; set; }
        public int? Tp { get; set; }
        public int? Co2 { get; set; }
        public string Poznamka { get; set; }
        public DateTime? NewD { get; set; }
        public string NewU { get; set; }
        public DateTime? ModifD { get; set; }
        public string ModifU { get; set; }
        public DateTime? Reftime { get; set; }
        public DateTime? DeleteD { get; set; }
        public string DeleteU { get; set; }
        public int? Azoxystrobin { get; set; }
        public int? Carbendazim { get; set; }
        public int? Cyproconazole { get; set; }
        public int? Dimethomorph { get; set; }
        public int? Epoxiconazole { get; set; }
        public int? Fenarimol { get; set; }
        public int? Fenhexamid { get; set; }
        public int? Fenpropidin { get; set; }
        public int? Fenpropimorph { get; set; }
        public int? Flusilazole { get; set; }
        public int? Iprodion { get; set; }
        public int? KresoximMethyl { get; set; }
        public int? Metalaxyl { get; set; }
        public int? Metconazole { get; set; }
        public int? Prochloraz { get; set; }
        public int? Propiconazole { get; set; }
        public int? Pyrimethanil { get; set; }
        public int? Spiroxamine { get; set; }
        public int? Tebuconazole { get; set; }
        public int? ThiophanateMethyl { get; set; }
        public int? Triadimefon { get; set; }
        public int? Triadimenol { get; set; }
        public int? Triforine { get; set; }
        public int? Triticonazole { get; set; }
        public int? _26Dichlorobenzamide { get; set; }
        public int? _2AminoNIsopropylBenzamide { get; set; }
        public int? _34Dichloranilin { get; set; }
        public int? Ampa { get; set; }
        public int? Bentazone { get; set; }
        public int? BentazoneMethyl { get; set; }
        public int? Bromacil { get; set; }
        public int? Bromoxynil { get; set; }
        public int? Clomazone { get; set; }
        public int? Dichlobenil { get; set; }
        public int? Dimethenamide { get; set; }
        public int? Ethofumesate { get; set; }
        public int? Florasulam { get; set; }
        public int? FluazifopP { get; set; }
        public int? FluazifopPButyl { get; set; }
        public int? Fluroxypyr { get; set; }
        public int? Foramsulfuron { get; set; }
        public int? Glyphosate { get; set; }
        public int? Chlorantraniliprol { get; set; }
        public int? Chlorbromuron { get; set; }
        public int? Chloridazon { get; set; }
        public int? ChloridazonDesphenyl { get; set; }
        public int? ChloridazonMethylDesphenyl { get; set; }
        public int? Chlorotoluron { get; set; }
        public int? ChlorotoluronDesmethyl { get; set; }
        public int? ImazamethabenzMethyl { get; set; }
        public int? Imazamox { get; set; }
        public int? Imazethapyr { get; set; }
        public int? Lenacil { get; set; }
        public int? Metoxuron { get; set; }
        public int? Napropamide { get; set; }
        public int? Pendimethalin { get; set; }
        public int? PropoxycarbazoneSodium { get; set; }
        public int? Propyzamide { get; set; }
        public int? Pyridate { get; set; }
        public int? Sulfosulfuron { get; set; }
        public int? Triallate { get; set; }
        public int? _2Chloro26Diethylacetanilide { get; set; }
        public int? Acetochlor { get; set; }
        public int? AcetochlorEsa { get; set; }
        public int? AcetochlorOa { get; set; }
        public int? Alachlor { get; set; }
        public int? AlachlorEsa { get; set; }
        public int? AlachlorOa { get; set; }
        public int? Dimethachlor { get; set; }
        public int? Metazachlor { get; set; }
        public int? MetazachlorEsa { get; set; }
        public int? MetazachlorOa { get; set; }
        public int? Metolachlor { get; set; }
        public int? MetolachlorEsa { get; set; }
        public int? MetolachlorOa { get; set; }
        public int? _3Hydroxycarbofuran { get; set; }
        public int? Carbofuran { get; set; }
        public int? Diazinon { get; set; }
        public int? Dimethoat { get; set; }
        public int? Chlorfenvinphos { get; set; }
        public int? Chlorpyrifos { get; set; }
        public int? Imidacloprid { get; set; }
        public int? Methamidophos { get; set; }
        public int? Methidathion { get; set; }
        public int? Methoxyfenozide { get; set; }
        public int? Phorate { get; set; }
        public int? Phosalone { get; set; }
        public int? Phosphamidon { get; set; }
        public int? Pirimicarb { get; set; }
        public int? Thiamethoxam { get; set; }
        public int? _34DichlorophenylUreaDcpu { get; set; }
        public int? Desmedipham { get; set; }
        public int? Diuron { get; set; }
        public int? DiuronDesmethylDcpmu { get; set; }
        public int? Isoproturon { get; set; }
        public int? IsoproturonDesmethyl { get; set; }
        public int? IsoproturonMonodesmethyl { get; set; }
        public int? Linuron { get; set; }
        public int? Methabenzthiazuron { get; set; }
        public int? Metobromuron { get; set; }
        public int? MetsulfuronMethyl { get; set; }
        public int? Monolinuron { get; set; }
        public int? Nicosulfuron { get; set; }
        public int? PIsopropylanilin { get; set; }
        public int? Rimsulfuron { get; set; }
        public int? _245TrichlorfenoxyoctovaKyselina { get; set; }
        public int? _24DichlorfenoxyoctovaKyselina { get; set; }
        public int? _24DpDichlorprop { get; set; }
        public int? Aminopyralid { get; set; }
        public int? Clopyralid { get; set; }
        public int? Dicamba { get; set; }
        public int? Mcpa { get; set; }
        public int? Mcpb { get; set; }
        public int? McppMecoprop { get; set; }
        public int? Picloram { get; set; }
        public int? AlfaHch { get; set; }
        public int? BetaHch { get; set; }
        public int? DeltaHch { get; set; }
        public int? EpsilonHch { get; set; }
        public int? GamaHch { get; set; }
        public int? OPDdd { get; set; }
        public int? OPDde { get; set; }
        public int? OPDdt { get; set; }
        public int? PPDdd { get; set; }
        public int? PPDde { get; set; }
        public int? PPDdt { get; set; }
        public int? Pcb101 { get; set; }
        public int? Pcb118 { get; set; }
        public int? Pcb138 { get; set; }
        public int? Pcb153 { get; set; }
        public int? Pcb180 { get; set; }
        public int? Pcb28 { get; set; }
        public int? Pcb52 { get; set; }
        public int? AlfaEndosulfan { get; set; }
        public int? Aldrin { get; set; }
        public int? BetaEndosulfan { get; set; }
        public int? CisHeptachlorepoxid { get; set; }
        public int? CisChlordan { get; set; }
        public int? Dieldrin { get; set; }
        public int? EndosulfanSulfat { get; set; }
        public int? Endrin { get; set; }
        public int? Heptachlor { get; set; }
        public int? Isodrin { get; set; }
        public int? Methoxychlor { get; set; }
        public int? Mirex { get; set; }
        public int? Oktachlorstyren { get; set; }
        public int? OxyChlordan { get; set; }
        public int? TransHeptachlorepoxid { get; set; }
        public int? TransChlordan { get; set; }
        public int? Trifluralin { get; set; }
        public int? Ametryn { get; set; }
        public int? Atraton { get; set; }
        public int? Atrazin { get; set; }
        public int? AtrazinDesethyl { get; set; }
        public int? AtrazinDesisopropyl { get; set; }
        public int? AtrazinHydroxy { get; set; }
        public int? Cyanazine { get; set; }
        public int? Desmetryn { get; set; }
        public int? AtrazinDesethylDesisopropyl { get; set; }
        public int? Hexazinon { get; set; }
        public int? Chlorsulfuron { get; set; }
        public int? Metamitron { get; set; }
        public int? Methoprotryn { get; set; }
        public int? Metribuzin { get; set; }
        public int? MetribuzinDesaminoDiketo { get; set; }
        public int? MetribuzinDesamino { get; set; }
        public int? MetribuzinDiketo { get; set; }
        public int? Prometon { get; set; }
        public int? Prometryn { get; set; }
        public int? Propachlor { get; set; }
        public int? PropachlorEsa { get; set; }
        public int? PropachlorOa { get; set; }
        public int? Propazin { get; set; }
        public int? Sebutylazin { get; set; }
        public int? Simazin { get; set; }
        public int? Simazin2Hydroxy { get; set; }
        public int? Simetryn { get; set; }
        public int? Terbutryn { get; set; }
        public int? Terbutylazin { get; set; }
        public int? TerbutylazinDesethyl { get; set; }
        public int? TerbutylazinDesethyl2Hydroxy { get; set; }
        public int? TerbutylazinHydroxy { get; set; }
        public int? ThifensulfuronMethyl { get; set; }
        public int? Triasulfuron { get; set; }
        public int? TribenuronMethyl { get; set; }
        public double? Tetrachlorobenzen1234 { get; set; }
        public double? Tetrachlorobenzen1235Plus1245 { get; set; }
        public int? _3Chlor4Methylanilin { get; set; }
        public int? Caffeine { get; set; }
        public int? Carbamazepin { get; set; }
        public int? Diethyltoluamid { get; set; }
        public int? Dichlormid { get; set; }
        public int? Dimethipin { get; set; }
        public int? Sulfamethoxazol { get; set; }
    }
}
