using System;
using System.Collections.Generic;

namespace SisWeb.EF.Models
{
    public partial class Pesticidy
    {
        public int PesticidyId { get; set; }
        public int? ObjektId { get; set; }
        public DateTime? Odber { get; set; }
        public double? HloubkaOdberu { get; set; }
        public string TypOdberu { get; set; }
        public string Realizace { get; set; }
        public string Protokol { get; set; }
        public string Vzorek { get; set; }
        public string VzorekTyp { get; set; }
        public double? _3Chlor4Methylanilin { get; set; }
        public double? Caffeine { get; set; }
        public double? Carbamazepin { get; set; }
        public double? Diethyltoluamid { get; set; }
        public double? Dichlormid { get; set; }
        public double? Dimethipin { get; set; }
        public double? Sulfamethoxazol { get; set; }
        public double? Azoxystrobin { get; set; }
        public double? Carbendazim { get; set; }
        public double? Cyproconazole { get; set; }
        public double? Dimethomorph { get; set; }
        public double? Epoxiconazole { get; set; }
        public double? Fenarimol { get; set; }
        public double? Fenhexamid { get; set; }
        public double? Fenpropidin { get; set; }
        public double? Fenpropimorph { get; set; }
        public double? Flusilazole { get; set; }
        public double? Iprodion { get; set; }
        public double? KresoximMethyl { get; set; }
        public double? Metalaxyl { get; set; }
        public double? Metconazole { get; set; }
        public double? Prochloraz { get; set; }
        public double? Propiconazole { get; set; }
        public double? Pyrimethanil { get; set; }
        public double? Spiroxamine { get; set; }
        public double? Tebuconazole { get; set; }
        public double? ThiophanateMethyl { get; set; }
        public double? Triadimefon { get; set; }
        public double? Triadimenol { get; set; }
        public double? Triforine { get; set; }
        public double? Triticonazole { get; set; }
        public double? _26Dichlorobenzamide { get; set; }
        public double? _2AminoNIsopropylBenzamide { get; set; }
        public double? _34Dichloranilin { get; set; }
        public double? Ampa { get; set; }
        public double? Bentazone { get; set; }
        public double? BentazoneMethyl { get; set; }
        public double? Bromacil { get; set; }
        public double? Bromoxynil { get; set; }
        public double? Clomazone { get; set; }
        public double? Dichlobenil { get; set; }
        public double? Dimethenamide { get; set; }
        public double? Ethofumesate { get; set; }
        public double? Florasulam { get; set; }
        public double? FluazifopP { get; set; }
        public double? FluazifopPButyl { get; set; }
        public double? Fluroxypyr { get; set; }
        public double? Foramsulfuron { get; set; }
        public double? Glyphosate { get; set; }
        public double? Chlorantraniliprol { get; set; }
        public double? Chlorbromuron { get; set; }
        public double? Chloridazon { get; set; }
        public double? ChloridazonDesphenyl { get; set; }
        public double? ChloridazonMethylDesphenyl { get; set; }
        public double? Chlorotoluron { get; set; }
        public double? ChlorotoluronDesmethyl { get; set; }
        public double? ImazamethabenzMethyl { get; set; }
        public double? Imazamox { get; set; }
        public double? Imazethapyr { get; set; }
        public double? Lenacil { get; set; }
        public double? Metoxuron { get; set; }
        public double? Napropamide { get; set; }
        public double? Pendimethalin { get; set; }
        public double? PropoxycarbazoneSodium { get; set; }
        public double? Propyzamide { get; set; }
        public double? Pyridate { get; set; }
        public double? Sulfosulfuron { get; set; }
        public double? Triallate { get; set; }
        public double? _2Chloro26Diethylacetanilide { get; set; }
        public double? Acetochlor { get; set; }
        public double? AcetochlorEsa { get; set; }
        public double? AcetochlorOa { get; set; }
        public double? Alachlor { get; set; }
        public double? AlachlorEsa { get; set; }
        public double? AlachlorOa { get; set; }
        public double? Dimethachlor { get; set; }
        public double? Metazachlor { get; set; }
        public double? MetazachlorEsa { get; set; }
        public double? MetazachlorOa { get; set; }
        public double? Metolachlor { get; set; }
        public double? MetolachlorEsa { get; set; }
        public double? MetolachlorOa { get; set; }
        public double? _3Hydroxycarbofuran { get; set; }
        public double? Carbofuran { get; set; }
        public double? Diazinon { get; set; }
        public double? Dimethoat { get; set; }
        public double? Chlorfenvinphos { get; set; }
        public double? Chlorpyrifos { get; set; }
        public double? Imidacloprid { get; set; }
        public double? Methamidophos { get; set; }
        public double? Methidathion { get; set; }
        public double? Methoxyfenozide { get; set; }
        public double? Phorate { get; set; }
        public double? Phosalone { get; set; }
        public double? Phosphamidon { get; set; }
        public double? Pirimicarb { get; set; }
        public double? Thiamethoxam { get; set; }
        public double? _34DichlorophenylUreaDcpu { get; set; }
        public double? Desmedipham { get; set; }
        public double? Diuron { get; set; }
        public double? DiuronDesmethylDcpmu { get; set; }
        public double? Isoproturon { get; set; }
        public double? IsoproturonDesmethyl { get; set; }
        public double? IsoproturonMonodesmethyl { get; set; }
        public double? Linuron { get; set; }
        public double? Methabenzthiazuron { get; set; }
        public double? Metobromuron { get; set; }
        public double? MetsulfuronMethyl { get; set; }
        public double? Monolinuron { get; set; }
        public double? Nicosulfuron { get; set; }
        public double? PIsopropylanilin { get; set; }
        public double? Rimsulfuron { get; set; }
        public double? _245TrichlorfenoxyoctovaKyselina { get; set; }
        public double? _24DichlorfenoxyoctovaKyselina { get; set; }
        public double? _24DpDichlorprop { get; set; }
        public double? Aminopyralid { get; set; }
        public double? Clopyralid { get; set; }
        public double? Dicamba { get; set; }
        public double? Mcpa { get; set; }
        public double? Mcpb { get; set; }
        public double? McppMecoprop { get; set; }
        public double? Picloram { get; set; }
        public double? AlfaHch { get; set; }
        public double? BetaHch { get; set; }
        public double? DeltaHch { get; set; }
        public double? EpsilonHch { get; set; }
        public double? GamaHch { get; set; }
        public double? OPDdd { get; set; }
        public double? OPDde { get; set; }
        public double? OPDdt { get; set; }
        public double? PPDdd { get; set; }
        public double? PPDde { get; set; }
        public double? PPDdt { get; set; }
        public double? Pcb101 { get; set; }
        public double? Pcb118 { get; set; }
        public double? Pcb138 { get; set; }
        public double? Pcb153 { get; set; }
        public double? Pcb180 { get; set; }
        public double? Pcb28 { get; set; }
        public double? Pcb52 { get; set; }
        public double? AlfaEndosulfan { get; set; }
        public double? Aldrin { get; set; }
        public double? BetaEndosulfan { get; set; }
        public double? CisHeptachlorepoxid { get; set; }
        public double? CisChlordan { get; set; }
        public double? Dieldrin { get; set; }
        public double? EndosulfanSulfat { get; set; }
        public double? Endrin { get; set; }
        public double? Heptachlor { get; set; }
        public double? Isodrin { get; set; }
        public double? Methoxychlor { get; set; }
        public double? Mirex { get; set; }
        public double? Oktachlorstyren { get; set; }
        public double? OxyChlordan { get; set; }
        public double? TransHeptachlorepoxid { get; set; }
        public double? TransChlordan { get; set; }
        public double? Trifluralin { get; set; }
        public double? Ametryn { get; set; }
        public double? Atraton { get; set; }
        public double? Atrazin { get; set; }
        public double? AtrazinDesethyl { get; set; }
        public double? AtrazinDesisopropyl { get; set; }
        public double? AtrazinHydroxy { get; set; }
        public double? Cyanazine { get; set; }
        public double? Desmetryn { get; set; }
        public double? AtrazinDesethylDesisopropyl { get; set; }
        public double? Hexazinon { get; set; }
        public double? Chlorsulfuron { get; set; }
        public double? Metamitron { get; set; }
        public double? Methoprotryn { get; set; }
        public double? Metribuzin { get; set; }
        public double? MetribuzinDesaminoDiketo { get; set; }
        public double? MetribuzinDesamino { get; set; }
        public double? MetribuzinDiketo { get; set; }
        public double? Prometon { get; set; }
        public double? Prometryn { get; set; }
        public double? Propachlor { get; set; }
        public double? PropachlorEsa { get; set; }
        public double? PropachlorOa { get; set; }
        public double? Propazin { get; set; }
        public double? Sebutylazin { get; set; }
        public double? Simazin { get; set; }
        public double? Simazin2Hydroxy { get; set; }
        public double? Simetryn { get; set; }
        public double? Terbutryn { get; set; }
        public double? Terbutylazin { get; set; }
        public double? TerbutylazinDesethyl { get; set; }
        public double? TerbutylazinDesethyl2Hydroxy { get; set; }
        public double? TerbutylazinHydroxy { get; set; }
        public double? ThifensulfuronMethyl { get; set; }
        public double? Triasulfuron { get; set; }
        public double? TribenuronMethyl { get; set; }
        public string Poznamka { get; set; }
        public DateTime? NewD { get; set; }
        public string NewU { get; set; }
        public DateTime? ModifD { get; set; }
        public string ModifU { get; set; }
        public DateTime? Reftime { get; set; }
        public DateTime? DeleteD { get; set; }
        public string DeleteU { get; set; }
    }
}
